version: "3"
services:
  mytb:
    container_name: mytb
    environment:
      TB_QUEUE_TYPE: in-memory
    image: "thingsboard/tb-postgres:3.2.2"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    restart: unless-stopped
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard

volumes:
  mytb-data:
  mytb-logs:
